<?php

if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
// log out after 30 minutes of session inactivity
if (isset($_SESSION['LAST_ACTIVITY']) && ((time() - $_SESSION['LAST_ACTIVITY']) > 1800)) {
    session_unset();
    session_destroy();
    header('Location: index.php');
}
?>
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Spécimen propose un large choix de chaussures confortables pour hommes et femmes." />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=DM+Serif+Text|Montserrat|Open+Sans|Poiret+One&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="css/normalize.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />

    <title>Specimen, votre boutique de chaussures sur Aix les Bains !</title>
</head>

<body>
    <header class="container">
        <div class="admin_nav">
            <?php if (isset($_SESSION['admin'])) : ?>
                <a class="admin_nav_panel" href="admin.php" title="Panneau de configuration">Admin Panel</a>
                <a class="admin_nav_panel" href="logout.php" title="Déconnexion">Se déconnecter <i class="fas fa-sign-out-alt"></i></a>
            <?php else : ?>
                <a class="admin_nav_panel" href="login.php" title="Se connecter"><i class="fas fa-cogs"></i>Administration</a>
            <?php endif ?>
        </div>
        <button id="to-Top"><i class="fas fa-arrow-up"></i></button>
        <div id="title">
            <h1>Specimen</h1>
            <small>Chausseur depuis 1954</small>
        </div>
        <div class="nav-mobile">
            <a href="#!" class="navbar-toggle" id="js-nav-toggle" title="Déroulez le menu">
                <span></span> </a>
        </div>
        <div id="nav_space">
            <nav id="top_nav" class="top_nav navbar stroke container">

                <ul class="main-nav" id="js-menu">
                    <li><a class="nav-links" href="index.php" title="Accueil">Accueil</a></li>
                    <li><a class="nav-links" href="products.php" title="Collection">Collection</a></li>
                    <!--    <li><a class="nav-links" href="#" title="Programme de fidélité">Programme de fidélité</a></li>  -->
                    <li><a class="nav-links" href="contact.php" title="Contactez-nous">Contact</a></li>
                    <!--    <li><a class="nav-links" href="#" title="Historique de la boutique">Qui sommes-nous ?</a></li>    -->
                </ul>
            </nav>
        </div>
    </header>
    <div style="position: absolute; left: 50%; z-index: 9999">
        <?php if (isset($_SESSION['flash'])) : ?>
            <?php foreach ($_SESSION['flash'] as $type => $message) : ?>
                <div id="log_notif" class="<?= $type; ?>">
                    <?= htmlspecialchars($message); ?>
                </div>
            <?php endforeach; ?>
            <?php unset($_SESSION['flash']); ?>
        <?php endif; ?>
    </div>
    <main>
        <?= $pageContent ?>
    </main>
    <footer>
        <div class="container" id="footer_area">
            <nav id="footer_nav">
                <h3>Menu</h3>
                <ul>
                    <li><a href="index.php" title="Accueil">Accueil</a></li>
                    <li><a href="products.php" title="Collection">Collection</a></li>
                    <!--    <li><a href="#" title="Programme de fidélité">Programme de fidélité</a></li>  -->
                    <li><a href="contact.php" title="Contact">Contact</a></li>
                    <!--   <li><a href="#" title="Historique de la boutique">Qui sommes-nous?</a></li>    -->
                </ul>
            </nav>
            <div id="footer_infos">
                <article id="footer_contact">
                    <h3>Contact</h3>
                    <p>Specimen</p>
                    <p>28 Avenue du Petit Port, 73100 Aix-les-Bains</p>
                    <p>06 01 06 04 08</p>
                    <p>contact@specimen.fr</p>

                </article>
                <article id="footer_schedule">
                    <h3>Horaires</h3>
                    <p>Ouvert du Mardi au Dimanche 9h-12h / 13h-17h</p>
                </article>
            </div>
        </div>
        <p class="copyright">Copyright © specimen 2019 - Réalisé par <a href="https://christiansaez.fr" title="Site développé par Christian Saez">Christian Saez</a> – Tous droits réservés</p>
    </footer>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript" src="js/script.js"></script>

</html>