<form class="form container" action="" method="post">
    <fieldset>
        <legend>Nom d'utilisateur</legend>
        <label>
            <input class="form-input" type="text" placeholder="Nom d'utilisateur" name="username" required>
        </label>
    </fieldset>
    <fieldset>
        <legend>Mot de passe</legend>
        <label>
            <input class="form-input" type="password" placeholder="Mot de passe" name="password" required>
        </label>
    </fieldset>
    
    <button class="btn btn-product admin-btn" type="submit" name="submit">Connexion</button>

</form>